name = "tools-generate-link"
main = "src/index.js"
compatibility_date = "2026-01-26"

# KV Binding - GANTI ID INI
[[kv_namespaces]]
binding = "LINKS_DB"
id = "1b74ffb788934a518e3561bfd42bd8a6"

# Environment Variables
[vars]
DOMAIN = "domainanda.com"
ADMIN_KEY = "admin"
